# Generated by Django 4.2.3 on 2023-07-21 00:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('feed_url', models.URLField(max_length=2000, unique=True)),
                ('type', models.CharField(choices=[('rss', 'RSS Feed')], max_length=10)),
                ('contact', models.EmailField(blank=True, max_length=500)),
                ('last_checked', models.DateTimeField()),
                ('author', models.CharField(blank=True, max_length=256)),
                ('title', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('posted', models.DateTimeField()),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='content.source')),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_check', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_text', models.TextField(blank=True)),
                ('staleness_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
