# Generated by Django 4.2.3 on 2023-07-25 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial_squashed_20230720'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(choices=[('1.11', '1.11'), ('2.2', '2.2'), ('3.0', '3.0'), ('3.1', '3.1'), ('3.2', '3.2'), ('4.0', '4.0'), ('4.1', '4.1'), ('4.2', '4.2'), ('5.0', '5.0')], max_length=10, unique=True)),
                ('released', models.DateTimeField()),
                ('end_of_life', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoTaggedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('django_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_posts', to='content.djangotag')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_posts', to='content.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='django_tags',
            field=models.ManyToManyField(blank=True, related_name='posts', through='content.DjangoTaggedPost', to='content.djangotag'),
        ),
        migrations.AddConstraint(
            model_name='djangotaggedpost',
            constraint=models.UniqueConstraint(fields=('django_tag', 'post'), name='djangotaggedpost_djangotag_post_unq'),
        ),
    ]
