# Generated by Django 4.2.3 on 2023-07-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '20230722_tag_alter_djangotaggedpost_django_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedpost',
            old_name='verified',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='djangotaggedpost',
            old_name='verified',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='djangotaggedpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
